spring:
  datasource:
    driverClassName: org.postgresql.Driver    
    url: jdbc:postgresql://172.16.64.133/tcs
    username: modulo3
    password: modulo3

server:
   port: 8080
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #https://proyecto9676.herokuapp.com/eureka 
  instance:
    hostname: localhost
    nonSecurePort: 8080

banner:
  location: classpath:/example/banner.txt
